# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('attend_day', models.CharField(max_length=100)),
                ('attend_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='attend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.Student'),
        ),
    ]
