# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_auto_20171108_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_day_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_time_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attend',
            name='attend_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.AttendDay'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='attend_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.AttendTime'),
        ),
    ]
